### ISSUE TITLE
tcp查询断开连接的问题

### ISSUE THREAD

**Issue by SIGLALALA** [TitenWang/dnspod-sr-comment#1]
看了您的源码注释，当用户以tcp请求时，如果该域名没有缓存，则断开连接。我测试发现，断开连接后，dnspod会去请求该域名，然后缓存下来。当用户再次请求该域名（tcp/udp），就会得到结果了。我想知道这种靠客户端重传的机制使用起来会有问题吗？

我是小白一个，期待您的解答，不喜勿喷。谢谢啦~~~

**Comment by TitenWang** [comment]
当客户端以tcp来发送dns请求的时候，dnspod如果没有缓存对应的信息，dnspod会断开和客户端之间的连接，但是仍然会将请求加入到hash表中，quizzer线程会从中取出请求去授权dns服务器查询，查询到之后会缓存到本地。具体为啥要断开dnspod服务器和客户端的连接我也是有点疑惑的，真正原因不清楚。
　　另外，你在问题中说“当用户再次请求该域名（tcp/udp），就会得到结果了。我想知道这种靠客户端重传的机制使用起来会有问题吗？”，我的理解是，当dnspod断开和客户端的连接后，客户端再次向dnspod服务器发起请求能获取到域名信息，这样就不算是重传了，因为这已经是两个不同的连接了。以tcp为例，假设A和B在进行数据交互，A给B发了个某个报文，但是B一直没有给A回ack，A在一定的时间后就会再给B发送同样的报文，这个时候还是在同一个连接之内，这个叫做重传。这和dnspod断开和客户端的连接，客户端再次发起请求不同。
